[package]
name = "cubes"
version = "0.1.0"
authors = ["David Campbell <dcampbell24@gmail.com>"]

[dependencies]
cake = { git = "https://github.com/ticki/cake.git" }

[[bin]]
name = "cake"
path = "cakefile.rs"

[[bin]]
name = "cubes-rs"
path = "src/main.rs"
