[package]
name = "cubes-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
clap = { version = "4.0", features = ["derive"] }
eframe = "0.19.0"
egui = "0.19.0"
env_logger = "0.9"
kiss3d = "0.35"
nalgebra = { version = "0.30", features = ["io", "sparse"] }
ron = "0.8.0"
serde = { version = "1", features = ["derive"] }

[[bin]]
name = "draw"
path = "src/draw/bin/main.rs"

[[bin]]
name = "input"
path = "src/input/bin/main.rs"

[[bin]]
name = "make_obj"
path = "src/make_obj/bin/main.rs"

[[bin]]
name = "solve"
path = "src/solve/bin/main.rs"
