[package]
name = "cubes"
description = "Applications for determining how to put a cube together."
version = "1.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["cubes"]
homepage = "https://github.com/dcampbell24/cubes"
# documentation = "https://docs.rs/cubes"
repository = "https://github.com/dcampbell24/cubes/tree/master/cubes-rs"
readme = "README.md"

[profile.release]
lto = true
# panic = "abort"
# opt-level = "z" // optimize for size
# strip = true
# codegen-units = 1

# RUSTFLAGS="-C target-cpu=native" 
# debug = true

[build-dependencies]
directories = "4"

[dependencies]
bincode = "1"
clap = { version = "4.0", features = ["derive"] }
criterion = { version = "0.3", features = ["html_reports"] }
directories = "4"
eframe = "0.19"
egui = "0.19"
env_logger = "0.9"
kiss3d = "0.35"
log = "0.4"
nalgebra = { version = "0.30", features = ["io", "sparse"] }
serde = { version = "1", features = ["derive"] }

[[bench]]
name = "benchmark_cubes"
harness = false

[[bin]]
name = "draw"
path = "src/draw/bin/main.rs"

[[bin]]
name = "input"
path = "src/input/bin/main.rs"

[[bin]]
name = "solve"
path = "src/solve/bin/main.rs"
